apiVersion: v1
kind: Pod
metadata:
  namespace: changeme
  name: postgres-client
  labels:
    app: postgres-client
spec:
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  containers:
  - name: postgres-client
    image: postgres
    env:
    - name: PGHOST
      value: "changeme"
    - name: PGDATABASE
      value: "changeme"
    - name: PGUSER
      value: "changeme"
    - name: POSTGRES_PASSWORD
      value: "changeme"
    stdin: true
    tty: true
